### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by joehi**
## Description

Please explain the detailed changes you made here.
Reference any issue number this pull request fixes.

## Checklist
- [x ] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by zonky2** [comment]
@joehi please create a account at transifex and we can you add to MM team

**Comment by joehi** [comment]
Okay, I created an account at transiflex and requested to join the MM team.

**Comment by zonky2** [comment]
you should be able to change the German texts... at transifex you have to "click" a bit to understand where what is...

**Comment by joehi** [comment]
I tried, but it seems I do not have enough permissions yet. I get the error message: "You do not have permissions to modify reviewed strings.".

**Comment by zonky2** [comment]
uff... and now?

**Comment by joehi** [comment]
No change, still the same error message.

**Comment by zonky2** [comment]
hmm.. :( I see you as translator 

the adoption of settings at Transifex is sometimes very slow - we'll see again tomorrow

**Comment by joehi** [comment]
Okay. Let's see. Another challenge to be solved. ;)

**Comment by discordier** [comment]
@zonky2 you have to add him to the reviewers team.

**Comment by joehi** [comment]
Die hier bei Github gemachten Korrekturen sowie viele weitere habe ich als Vorschlag bei Transiflex eintragen können, was ich dann auch gemacht habe. Aber es ist mühsam, die Textstellen zu finden. Ich habe dort keine Suchfunktion für Strings gefunden.
Und einen Text aus MetaModels/attribute_file
src/Resources/contao/languages/de/tl_metamodel_attribute.php habe ich gar nicht gefunden.

**Comment by joehi** [comment]
@discordier Thank you, it works. Now I can save the corrections I suggested.

**Comment by joehi** [comment]
Now all the corrections should be activated at Transiflex.

**Pull request closed without merging**
